Repository TeamAmaze/AmazeFileManager, pull requests merged in 2018-06, with the labels that each got.

#1260 Fix possibility of archive entry extracted outside specified destination for 3.2.1
  app/src/main/java/com/amaze/filemanager/services/ExtractService.java
  app/src/main/java/com/amaze/filemanager/services/asynctasks/RarHelperTask.java
  app/src/main/java/com/amaze/filemanager/services/asynctasks/ZipHelperTask.java
Labels: severe

#1276 Bump version number to v3.2.2
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/res/values/translators.xml
Labels: severe

#1268 Null safety on EditText.getTypeFace() for API 15
  app/build.gradle
  app/src/androidTest/java/com/amaze/filemanager/activities/TextEditorActivityEspressoTest.java
  app/src/androidTest/java/com/amaze/filemanager/utils/files/CryptUtilTest.java
  app/src/main/java/com/amaze/filemanager/activities/TextEditorActivity.java
Labels: help wanted

#1291 Swap parameter order of saving SMB connection data to database
  app/src/main/java/com/amaze/filemanager/activities/MainActivity.java
Labels: high

#1258 Fix possibility of archive entry being extracted to outside extract destination
  app/build.gradle
  app/src/main/java/com/amaze/filemanager/asynchronous/asynctasks/compress/CompressedHelperTask.java
  app/src/main/java/com/amaze/filemanager/asynchronous/asynctasks/compress/GzipHelperTask.java
  app/src/main/java/com/amaze/filemanager/asynchronous/asynctasks/compress/RarHelperTask.java
  app/src/main/java/com/amaze/filemanager/asynchronous/asynctasks/compress/TarHelperTask.java
  app/src/main/java/com/amaze/filemanager/asynchronous/asynctasks/compress/ZipHelperTask.java
  app/src/main/java/com/amaze/filemanager/asynchronous/services/ExtractService.java
  app/src/main/java/com/amaze/filemanager/filesystem/compressed/CompressedHelper.java
  app/src/main/java/com/amaze/filemanager/filesystem/compressed/extractcontents/Extractor.java
  app/src/main/java/com/amaze/filemanager/filesystem/compressed/extractcontents/helpers/GzipExtractor.java
  app/src/main/java/com/amaze/filemanager/filesystem/compressed/extractcontents/helpers/RarExtractor.java
  app/src/main/java/com/amaze/filemanager/filesystem/compressed/extractcontents/helpers/TarExtractor.java
  app/src/main/java/com/amaze/filemanager/filesystem/compressed/extractcontents/helpers/ZipExtractor.java
  app/src/main/java/com/amaze/filemanager/filesystem/compressed/showcontents/helpers/GzipDecompressor.java
  app/src/main/java/com/amaze/filemanager/filesystem/compressed/showcontents/helpers/RarDecompressor.java
  app/src/main/java/com/amaze/filemanager/filesystem/compressed/showcontents/helpers/TarDecompressor.java
  app/src/main/java/com/amaze/filemanager/filesystem/compressed/showcontents/helpers/ZipDecompressor.java
  app/src/main/res/values-zh-rTW/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/amaze/filemanager/asynchronous/services/ExtractServiceTest.java
  app/src/test/java/com/amaze/filemanager/filesystem/compressed/B0rkenZipTest.java
  app/src/test/java/com/amaze/filemanager/filesystem/compressed/TestArchives.java
  app/src/test/java/com/amaze/filemanager/filesystem/compressed/extractcontents/AbstractExtractorTest.java
  app/src/test/java/com/amaze/filemanager/filesystem/compressed/extractcontents/ExtractorTestSuite.java
  app/src/test/java/com/amaze/filemanager/filesystem/compressed/extractcontents/RarExtractorTest.java
  app/src/test/java/com/amaze/filemanager/filesystem/compressed/extractcontents/TarExtractorTest.java
  app/src/test/java/com/amaze/filemanager/filesystem/compressed/extractcontents/TarGzExtractorTest.java
  app/src/test/java/com/amaze/filemanager/filesystem/compressed/extractcontents/ZipExtractorTest.java
  app/src/test/resources/test-archive.rar
  app/src/test/resources/test-archive.tar
  app/src/test/resources/test-archive.tar.gz
  app/src/test/resources/test-archive.zip
  app/src/test/resources/zip-slip-win.zip
  app/src/test/resources/zip-slip.zip
Labels: high
