Repository TeamAmaze/AmazeFileManager, pull requests merged in 2021-05, with the labels that each got.

#2440 Added App Name & Package to error reports
  app/src/main/java/com/amaze/filemanager/crashreport/ErrorActivity.java
Labels: Issue-Task (low)

#2341 DocumentFile-based FTP server implementation
  app/build.gradle
  app/src/main/java/com/amaze/filemanager/asynchronous/services/ftp/FtpReceiver.java
  app/src/main/java/com/amaze/filemanager/asynchronous/services/ftp/FtpReceiver.kt
  app/src/main/java/com/amaze/filemanager/asynchronous/services/ftp/FtpService.java
  app/src/main/java/com/amaze/filemanager/asynchronous/services/ftp/FtpService.kt
  app/src/main/java/com/amaze/filemanager/filesystem/ftpserver/AndroidFileSystemFactory.kt
  app/src/main/java/com/amaze/filemanager/filesystem/ftpserver/AndroidFtpFile.kt
  app/src/main/java/com/amaze/filemanager/filesystem/ftpserver/AndroidFtpFileSystemView.kt
  app/src/main/java/com/amaze/filemanager/ui/activities/MainActivity.java
  app/src/main/java/com/amaze/filemanager/ui/fragments/FtpServerFragment.java
  app/src/main/java/com/amaze/filemanager/ui/fragments/FtpServerFragment.kt
  app/src/main/java/com/amaze/filemanager/utils/MainActivityHelper.java
  app/src/test/java/com/amaze/filemanager/asynchronous/asynctasks/AbstractDeleteTaskTestBase.kt
  app/src/test/java/com/amaze/filemanager/asynchronous/services/FtpServiceTest.kt
  app/src/test/resources/simplelogger.properties
Labels: Area-FTP, Issue-Feature

#2444 Move IV value to build.gradle
  app/build.gradle
  app/src/androidTest/java/com/amaze/filemanager/filesystem/files/CryptUtilTest.java
  app/src/main/java/com/amaze/filemanager/filesystem/files/CryptUtil.java
Labels: Area-CodeHealth

#2445 Invert equality check of type when Intent is ACTION_SEND
  app/src/main/java/com/amaze/filemanager/ui/activities/MainActivity.java
Labels: Issue-Bug

#2447 Break down over long onCreateDialog()
  app/src/main/java/com/amaze/filemanager/ui/activities/MainActivity.java
  app/src/main/java/com/amaze/filemanager/ui/dialogs/SftpConnectDialog.kt
Labels: Area-CodeHealth, Area-Ssh/Scp/Sftp

#2291 Remove nullCheckOrInterrupt replacing it with better system
  app/src/main/java/com/amaze/filemanager/asynchronous/asynctasks/LoadFilesListTask.java
  app/src/main/java/com/amaze/filemanager/ui/activities/superclasses/BaseAsyncTask.java
Labels: Area-CodeHealth

#2480 ColorPref fixes: "Customize" missing colour, up button behaviour
  app/src/main/java/com/amaze/filemanager/ui/fragments/preference_fragments/ColorPref.kt
Labels: Area-UIUX, Issue-Bug, Issue-Glitch

#2463 Use JDK 11 to build
  .github/workflows/android-debug-artifact-ondemand.yml
  .github/workflows/android-debug-artifact-release.yml
  .github/workflows/android-feature.yml
  .github/workflows/android-main.yml
Labels: Area-CICD, Area-CodeHealth, Issue-Feature, Issue-Task (low)

#2462 Move library version number to top-level build.gradle
  app/build.gradle
  build.gradle
  file_operations/build.gradle
Labels: Area-CodeHealth

#2473 Fix check for available USB storage when USB plug/unplug event is triggered
  app/src/main/java/com/amaze/filemanager/ui/activities/MainActivity.java
  app/src/main/java/com/amaze/filemanager/utils/OTGUtil.java
  app/src/main/java/com/amaze/filemanager/utils/OTGUtil.kt
  app/src/main/java/com/amaze/filemanager/utils/OnFileFound.kt
Labels: Area-ExternalStorage, Issue-Bug

#2466 Kotlintize SSH related classes and fix HybridFile.getParent() for SSH files
  app/src/main/java/com/amaze/filemanager/asynchronous/asynctasks/ssh/GetSshHostFingerprintTask.java
  app/src/main/java/com/amaze/filemanager/asynchronous/asynctasks/ssh/GetSshHostFingerprintTask.kt
  app/src/main/java/com/amaze/filemanager/asynchronous/asynctasks/ssh/PemToKeyPairTask.java
  app/src/main/java/com/amaze/filemanager/asynchronous/asynctasks/ssh/PemToKeyPairTask.kt
  app/src/main/java/com/amaze/filemanager/asynchronous/asynctasks/ssh/SshAuthenticationTask.java
  app/src/main/java/com/amaze/filemanager/asynchronous/asynctasks/ssh/SshAuthenticationTask.kt
  app/src/main/java/com/amaze/filemanager/filesystem/HybridFile.java
  app/src/main/java/com/amaze/filemanager/filesystem/ssh/CustomSshJConfig.kt
  app/src/main/java/com/amaze/filemanager/filesystem/ssh/SFtpClientTemplate.java
  app/src/main/java/com/amaze/filemanager/filesystem/ssh/SFtpClientTemplate.kt
  app/src/main/java/com/amaze/filemanager/filesystem/ssh/SshClientSessionTemplate.java
  app/src/main/java/com/amaze/filemanager/filesystem/ssh/SshClientSessionTemplate.kt
  app/src/main/java/com/amaze/filemanager/filesystem/ssh/SshClientTemplate.java
  app/src/main/java/com/amaze/filemanager/filesystem/ssh/SshClientTemplate.kt
  app/src/main/java/com/amaze/filemanager/filesystem/ssh/SshClientUtils.java
  app/src/main/java/com/amaze/filemanager/filesystem/ssh/SshConnectionPool.java
  app/src/main/java/com/amaze/filemanager/filesystem/ssh/SshConnectionPool.kt
  app/src/main/java/com/amaze/filemanager/ui/activities/MainActivity.java
  app/src/main/java/com/amaze/filemanager/ui/dialogs/SftpConnectDialog.kt
  app/src/main/java/com/amaze/filemanager/ui/fragments/MainFragment.java
  app/src/test/java/com/amaze/filemanager/asynchronous/asynctasks/ssh/SshAuthenticationTaskTest.kt
  app/src/test/java/com/amaze/filemanager/filesystem/HybridFileTest.kt
  app/src/test/java/com/amaze/filemanager/filesystem/ssh/AbstractSftpServerTest.java
  app/src/test/java/com/amaze/filemanager/filesystem/ssh/SshConnectionPoolTest.java
  app/src/test/java/com/amaze/filemanager/filesystem/ssh/test/MockSshConnectionPools.kt
  app/src/test/java/com/amaze/filemanager/filesystem/ssh/test/TestKeyProvider.java
Labels: Area-Ssh/Scp/Sftp, Issue-Bug

#2496 Fix Apps list sort button and correct rebase mistakes at FtpService related classes
  app/src/main/java/com/amaze/filemanager/asynchronous/services/ftp/FtpService.kt
  app/src/main/java/com/amaze/filemanager/ui/activities/MainActivity.java
  app/src/main/java/com/amaze/filemanager/ui/fragments/FtpServerFragment.kt
  app/src/test/java/com/amaze/filemanager/asynchronous/services/FtpServiceTest.kt
Labels: Area-AppManager, Area-CodeHealth, Area-FTP, Issue-Bug

#2508 Suppress jetifier transform jar output during Github build
  .github/workflows/android-debug-artifact-ondemand.yml
  .github/workflows/android-debug-artifact-release.yml
  .github/workflows/android-feature.yml
  .github/workflows/android-main.yml
Labels: Area-CICD, Area-CodeHealth, Issue-Feature, Issue-Task (low)
