Repository TeamAmaze/AmazeFileManager, pull requests merged in 2021-11, with the labels that each got.

#2986 Update Google Billing library to 4.0
  app/src/main/java/com/amaze/filemanager/application/AppConfig.java
  app/src/main/res/values/strings.xml
  app/src/play/java/com/amaze/filemanager/utils/Billing.java
  build.gradle
Labels: Issue-Task (low), Area-CodeHealth

#3022 Fix wildcard imports failing CI build with unit tests
  app/src/test/java/com/amaze/filemanager/asynchronous/asynctasks/AbstractDeleteTaskTestBase.kt
  app/src/test/java/com/amaze/filemanager/asynchronous/asynctasks/compress/AbstractCompressedHelperTaskTest.kt
  app/src/test/java/com/amaze/filemanager/asynchronous/asynctasks/ssh/SshAuthenticationTaskTest.kt
  app/src/test/java/com/amaze/filemanager/asynchronous/asynctasks/texteditor/read/ReadTextFileCallableTest.kt
  app/src/test/java/com/amaze/filemanager/asynchronous/services/ExtractServiceTest.kt
  app/src/test/java/com/amaze/filemanager/asynchronous/services/ZipServiceTest.kt
  app/src/test/java/com/amaze/filemanager/filesystem/AbstractOperationsTestBase.kt
  app/src/test/java/com/amaze/filemanager/filesystem/files/FileUtilsTest.kt
  app/src/test/java/com/amaze/filemanager/filesystem/smb/SmbHybridFileTest.kt
  app/src/test/java/com/amaze/filemanager/filesystem/ssh/SshHybridFileTest.kt
  app/src/test/java/com/amaze/filemanager/ui/theme/AppThemeTest.kt
  app/src/test/java/com/amaze/filemanager/utils/MinMaxInputFilterTest.kt
Labels: Issue-Bug, Issue-Task (low), Area-CICD, Area-CodeHealth, Area-Test

#3018 Don't ask for storage permission on Android 11 or above
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/amaze/filemanager/ui/activities/MainActivity.java
  app/src/main/java/com/amaze/filemanager/ui/activities/superclasses/PermissionsActivity.java
Labels: Issue-Feature, Issue-Task (low), Area-UIUX, Environment-API30

#3006 chore: add sign config to .gitignore
  .gitignore
Labels: PR-NoCodeChanges

#3015 Fix open with dialog glitch
  app/src/main/java/com/amaze/filemanager/ui/base/BaseBottomSheetFragment.kt
Labels: Area-UIUX, Issue-Glitch
