Repository TeamAmaze/AmazeFileManager, pull requests merged in 2021-09, with the labels that each got.

#2785 Update history icon color
  app/src/main/res/drawable/ic_history_white_24dp.xml
Labels: Issue-Glitch

#2754 Add support for content:// URI in CompressedExplorerFragment
  app/src/main/java/com/amaze/filemanager/adapters/CompressedExplorerAdapter.java
  app/src/main/java/com/amaze/filemanager/filesystem/compressed/showcontents/Decompressor.kt
  app/src/main/java/com/amaze/filemanager/ui/drag/RecyclerAdapterDragListener.kt
  app/src/main/java/com/amaze/filemanager/ui/fragments/CompressedExplorerFragment.java
  app/src/main/java/com/amaze/filemanager/ui/fragments/CompressedExplorerFragment.kt
  app/src/main/java/com/amaze/filemanager/ui/fragments/data/CompressedExplorerFragmentViewModel.kt
  app/src/main/res/values/strings.xml
Labels: Issue-Bug, Issue-Severe (high), Area-Compression

#2773 Fixes #1555
  app/src/main/java/com/amaze/filemanager/ui/fragments/TabFragment.java
Labels: Issue-Bug

#2796 CompressedExplorerFragment refactorings
  app/src/main/java/com/amaze/filemanager/adapters/CompressedExplorerAdapter.java
  app/src/main/java/com/amaze/filemanager/ui/drag/RecyclerAdapterDragListener.kt
  app/src/main/java/com/amaze/filemanager/ui/fragments/CompressedExplorerFragment.kt
  app/src/main/java/com/amaze/filemanager/ui/fragments/MainFragment.java
  app/src/main/java/com/amaze/filemanager/utils/BottomBarButtonPath.kt
Labels: Issue-Task (low), Area-CodeHealth, Area-Compression

#2825 Google Drive compliance changes
  README.md
  app/src/main/java/com/amaze/filemanager/database/CloudHandler.java
  app/src/main/res/layout/fragment_sheet_cloud.xml
  app/src/main/res/values-be-rBY/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-eo/strings.xml
  app/src/main/res/values-es-rUS/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-eu-rES/strings.xml
  app/src/main/res/values-eu/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr-rCA/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-id/strings.xml
  app/src/main/res/values-is/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rHK/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
  app/src/main/res/values/strings.xml
Labels: Issue-Task (low), Issue-Severe (high), Area-UIUX, Area-Cloud

#2833 FIx hiding feature
  app/src/main/java/com/amaze/filemanager/ui/fragments/MainFragment.java
Labels: Issue-Bug

#2806 Fix MainActivity does not respond to view compressed file intents
  app/src/main/java/com/amaze/filemanager/adapters/RecyclerAdapter.java
  app/src/main/java/com/amaze/filemanager/filesystem/files/FileUtils.java
  app/src/main/java/com/amaze/filemanager/ui/activities/MainActivity.java
  app/src/main/java/com/amaze/filemanager/ui/dialogs/OpenFileDialogFragment.kt
  app/src/main/java/com/amaze/filemanager/ui/dialogs/SftpConnectDialog.kt
  app/src/main/java/com/amaze/filemanager/ui/icons/MimeTypes.java
Labels: Issue-Bug, Area-UIUX, Area-Compression

#2838 Minor Updates to Dialogs
  app/src/main/java/com/amaze/filemanager/ui/Extensions.kt
  app/src/main/java/com/amaze/filemanager/ui/dialogs/GeneralDialogCreation.java
  app/src/main/res/layout/dialog_encrypt_authenticate.xml
Labels: Area-UIUX

#2855 Fix tests after merging
  app/src/main/java/com/amaze/filemanager/asynchronous/asynctasks/texteditor/write/WriteTextFileCallable.java
  app/src/test/java/com/amaze/filemanager/ui/activities/TextEditorActivityTest.java
Labels: Issue-Bug, Issue-Task (low), Area-TextEditor, Area-Test
