Repository TeamAmaze/AmazeFileManager, pull requests merged in 2021-06, with the labels that each got.

#2519 Add handling for R.id.exit in AppsListFragment
  app/src/main/java/com/amaze/filemanager/ui/activities/MainActivity.java
  app/src/main/java/com/amaze/filemanager/ui/fragments/AppsListFragment.java
Labels: Area-AppManager, Area-CodeHealth, Issue-Bug, Issue-Task (low)

#2534 Fix FTP server status display
  app/src/main/java/com/amaze/filemanager/asynchronous/services/ftp/FtpService.kt
  app/src/main/java/com/amaze/filemanager/ui/fragments/FtpServerFragment.kt
Labels: Area-FTP, Area-UIUX, Issue-Bug

#2539 Fix ExternalSdCardOperation.getDocumentFile()
  app/src/main/java/com/amaze/filemanager/filesystem/ExternalSdCardOperation.kt
Labels: Area-ExternalStorage, Issue-Bug

#2598 Add SAF permission grant routine for FTP server first run
  app/src/main/java/com/amaze/filemanager/asynchronous/services/ftp/FtpService.kt
  app/src/main/java/com/amaze/filemanager/ui/fragments/FtpServerFragment.kt
  app/src/main/res/values/strings.xml
Labels: Area-FTP, Issue-Bug, Issue-Severe (high)

#2608 Fix value for legacy_listing_summary
  app/src/main/res/values/strings.xml
Labels: Area-UIUX, Issue-Bug, Issue-Task (low)

#2630 Updated icon color
  app/src/main/res/drawable/ic_shortcut_star.xml
Labels: Issue-Glitch

#2627 Persist URI to preference after choosing shared folder path
  app/src/main/java/com/amaze/filemanager/ui/fragments/FtpServerFragment.kt
  transifex.yml
Labels: Area-FTP, Issue-Bug

#2643 Bump 3.7
  app/build.gradle
  app/src/main/java/com/amaze/filemanager/ui/fragments/FtpServerFragment.kt
  app/src/main/res/drawable/ic_shortcut_star.xml
  app/src/main/res/values/translators.xml
Labels: Issue-Task (low)

#2644 Remove nullable bypasses with sensible defaults
  app/src/main/java/com/amaze/filemanager/ui/fragments/FtpServerFragment.kt
Labels: Area-FTP, Issue-Bug

#2616 Update Bouncycastle to 1.68, jcifs to 2.1.6
  app/build.gradle
  build.gradle
Labels: Area-CodeHealth, Issue-Feature, Issue-Task (low)
