Repository TeamAmaze/AmazeFileManager, pull requests merged in 2022-09, with the labels that each got.

#3483 Update fastlane
  fastlane/metadata/android/en-US/full_description.txt
  fastlane/metadata/android/en-US/images/icon.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/1.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/2.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/3.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/4.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/5.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/6.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/7.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/8.png
  fastlane/metadata/android/en-US/short_description.txt
Labels: PR-NoCodeChanges

#3487 Fix failing Espresso tests
  app/src/androidTest/java/com/amaze/filemanager/database/UtilsHandlerTest.java
  app/src/androidTest/java/com/amaze/filemanager/filesystem/files/CryptUtilTest.java
  app/src/androidTest/java/com/amaze/filemanager/ssh/SshClientUtilTest.java
Labels: Issue-Bug, Area-CodeHealth, Area-Test

#3494 Fix database migration for anonymous connections
  app/src/main/java/com/amaze/filemanager/database/UtilitiesDatabase.kt
  app/src/test/java/com/amaze/filemanager/database/UtilitiesDatabaseMigrationTest.kt
Labels: Issue-Bug, Area-Database

#3495 F-Droid friendly codebase
  app/src/test/java/com/amaze/filemanager/asynchronous/services/ExtractServiceTest.kt
  app/src/test/java/com/amaze/filemanager/filesystem/compressed/CompressedHelperTest.java
  app/src/test/java/com/amaze/filemanager/test/TestUtils.kt
  app/src/testFdroid/java/com/amaze/filemanager/asynchronous/asynctasks/compress/CompressedHelperCallableTestSuite.kt
  app/src/testFdroid/java/com/amaze/filemanager/filesystem/compressed/extractcontents/ExtractorTestSuite.kt
  app/src/testPlay/java/com/amaze/filemanager/asynchronous/asynctasks/compress/CompressedHelperCallableTestSuite.kt
  app/src/testPlay/java/com/amaze/filemanager/asynchronous/asynctasks/compress/EncryptedRarHelperCallableTest.kt
  app/src/testPlay/java/com/amaze/filemanager/asynchronous/asynctasks/compress/RarHelperCallableTest.kt
  app/src/testPlay/java/com/amaze/filemanager/filesystem/compressed/extractcontents/ExtractorTestSuite.kt
  app/src/testPlay/java/com/amaze/filemanager/filesystem/compressed/extractcontents/ListPasswordProtectedRarTest.kt
  app/src/testPlay/java/com/amaze/filemanager/filesystem/compressed/extractcontents/MultipartRarExtractorTest.kt
  app/src/testPlay/java/com/amaze/filemanager/filesystem/compressed/extractcontents/PasswordProtectedRarTest.kt
  app/src/testPlay/java/com/amaze/filemanager/filesystem/compressed/extractcontents/RarExtractorTest.kt
Labels: Issue-Task (low), Area-CodeHealth, Area-Test

#3501 Lower threshold of CustomNavigationView.isNavigationViewSavedStateMissing() down to API 19
  app/src/main/java/com/amaze/filemanager/ui/views/drawer/CustomNavigationView.java
Labels: Issue-Bug

#3502 Fix ExtractService use of Context
  app/src/main/java/com/amaze/filemanager/asynchronous/services/ExtractService.java
  app/src/test/java/com/amaze/filemanager/asynchronous/services/ExtractServiceTest.kt
Labels: Area-CodeHealth, Area-Compression

#3503 Use Completable instead of Flowable to refresh Drawer
  app/src/main/java/com/amaze/filemanager/ui/activities/MainActivity.java
  app/src/main/java/com/amaze/filemanager/ui/views/drawer/Drawer.java
Labels: Issue-Bug, Area-UIUX

#3509 Fix ExplorerDatabase migration
  app/src/main/java/com/amaze/filemanager/database/ExplorerDatabase.java
  app/src/main/java/com/amaze/filemanager/database/ExplorerDatabase.kt
  app/src/main/java/com/amaze/filemanager/database/UtilitiesDatabase.kt
  app/src/test/java/com/amaze/filemanager/database/ExplorerDatabaseMigrationTest.java
  app/src/test/java/com/amaze/filemanager/database/ExplorerDatabaseMigrationTest.kt
  app/src/test/resources/schemas/com.amaze.filemanager.database.ExplorerDatabase/9.json
Labels: Issue-Bug, Issue-Severe (high), Area-Cloud

#3521 Disable FtpHybridFileTests at all
  app/src/test/java/com/amaze/filemanager/filesystem/ftp/FtpHybridFileAnonymousLoginTest.kt
  app/src/test/java/com/amaze/filemanager/filesystem/ftp/FtpHybridFileTest.kt
Labels: Issue-Bug, Area-CodeHealth
