Repository TeamAmaze/AmazeFileManager, pull requests merged in 2022-03, with the labels that each got.

#3197 Fix build errors on Github Actions
  .github/workflows/android-main.yml
  app/.gitignore
  app/build.gradle
Labels: Issue-Severe (high), Area-CICD

#3204 Fix Android connected test compatibility with main code base
  app/src/androidTest/java/com/amaze/filemanager/asynchronous/services/ftp/FtpServiceEspressoTest.kt
  app/src/test/java/com/amaze/filemanager/asynchronous/services/ExtractServiceTest.kt
  build.gradle
Labels: Issue-Bug, Issue-Task (low), Area-CICD

#3211 Change cap words to cap sentences
  app/src/main/java/com/amaze/filemanager/ui/dialogs/GeneralDialogCreation.java
  app/src/main/res/layout/dialog_encrypt_authenticate.xml
  app/src/main/res/layout/dialog_singleedittext.xml
Labels: Issue-Task (low), Area-UIUX

#3188 Root based filesystem support for FTP server
  app/build.gradle
  app/src/androidTest/java/com/amaze/filemanager/asynchronous/services/ftp/FtpServiceEspressoTest.kt
  app/src/main/java/com/amaze/filemanager/asynchronous/services/ftp/FtpService.kt
  app/src/main/java/com/amaze/filemanager/crashreport/ErrorActivity.java
  app/src/main/java/com/amaze/filemanager/filesystem/files/FileUtils.java
  app/src/main/java/com/amaze/filemanager/filesystem/ftpserver/RootFileSystemFactory.kt
  app/src/main/java/com/amaze/filemanager/filesystem/ftpserver/RootFileSystemView.kt
  app/src/main/java/com/amaze/filemanager/filesystem/ftpserver/RootFtpFile.kt
  app/src/main/java/com/amaze/filemanager/filesystem/root/ListFilesCommand.kt
  app/src/main/java/com/amaze/filemanager/ui/activities/MainActivity.java
  app/src/main/java/com/amaze/filemanager/ui/dialogs/AlertDialog.kt
  app/src/main/java/com/amaze/filemanager/ui/dialogs/GeneralDialogCreation.java
  app/src/main/java/com/amaze/filemanager/ui/fragments/FtpServerFragment.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/com/amaze/filemanager/asynchronous/services/FtpServiceAndroidFileSystemIntegrationTest.kt
  app/src/test/java/com/amaze/filemanager/asynchronous/services/FtpServiceSupportedCiphersTest.kt
Labels: Issue-Bug, Area-FTP
