Repository TeamAmaze/AmazeFileManager, pull requests merged in 2023-10, with the labels that each got.

#3856 Fix broken media scanner
  app/src/main/java/com/amaze/filemanager/asynchronous/asynctasks/DeleteTask.java
  app/src/main/java/com/amaze/filemanager/asynchronous/asynctasks/movecopy/MoveFilesTask.kt
  app/src/main/java/com/amaze/filemanager/asynchronous/services/CopyService.java
  app/src/main/java/com/amaze/filemanager/filesystem/Operations.java
  app/src/main/java/com/amaze/filemanager/filesystem/files/FileUtils.java
  app/src/main/java/com/amaze/filemanager/filesystem/files/GenericCopyUtil.java
  app/src/main/java/com/amaze/filemanager/filesystem/files/MediaConnectionUtils.kt
  app/src/main/java/com/amaze/filemanager/ui/fragments/MainFragment.java
Labels: Issue-Severe (high)

#3935 Sanitize parameters to prevent path injection
  app/src/main/java/com/amaze/filemanager/filesystem/FileUtil.java
  app/src/main/java/com/amaze/filemanager/filesystem/root/MountPathCommand.kt
  app/src/main/java/com/amaze/filemanager/ui/activities/MainActivity.java
  app/src/main/java/com/amaze/filemanager/ui/fragments/CompressedExplorerFragment.kt
  app/src/main/res/values/strings.xml
Labels: Issue-Bug, Issue-Severe (high)

#3946 Force return IPv4 address when probing network interface for listening address
  app/src/main/java/com/amaze/filemanager/utils/NetworkUtil.kt
Labels: Issue-Bug, Area-FTP

#3954 Fix ClassCastException at SmbSearchDialog with SMB SubnetScanner
  app/src/main/res/layout/smb_computers_row.xml
Labels: Issue-Bug, Area-SMB, not-yet-rolled

#3960 Fix ls lines for (even more) legacy devices
  app/src/main/java/com/amaze/filemanager/filesystem/files/FileUtils.java
  app/src/test/java/com/amaze/filemanager/filesystem/files/FileUtilsTest.kt
Labels: Issue-Bug

#3964 Chore fixes in TextEditorActivity and FtpNotification
  app/src/main/java/com/amaze/filemanager/ui/activities/texteditor/TextEditorActivity.java
  app/src/main/java/com/amaze/filemanager/ui/notifications/FtpNotification.java
Labels: Area-CodeHealth

#3966 Fix "None on top" sort mode
  app/src/main/java/com/amaze/filemanager/adapters/RecyclerAdapter.java
  app/src/main/java/com/amaze/filemanager/asynchronous/asynctasks/LoadFilesListTask.java
  app/src/main/java/com/amaze/filemanager/filesystem/files/FileListSorter.java
  app/src/main/java/com/amaze/filemanager/filesystem/files/FileListSorter.kt
  app/src/main/java/com/amaze/filemanager/ui/fragments/data/MainFragmentViewModel.kt
  app/src/test/java/com/amaze/filemanager/filesystem/files/FileListSorterTest.java
  app/src/test/java/com/amaze/filemanager/filesystem/files/FileListSorterTest.kt
Labels: Issue-Bug, Area-UIUX

#3970 Chore: null guards
  app/src/main/java/com/amaze/filemanager/asynchronous/handlers/FileHandler.kt
  app/src/main/java/com/amaze/filemanager/ui/fragments/MainFragment.java
  app/src/main/java/com/amaze/filemanager/utils/DataUtils.java
Labels: Issue-Bug, Area-CodeHealth, Crash-NullPointerException

#3737 SDK 33 adaptations, language and library upgrades
  app/build.gradle
  app/src/androidTest/java/com/amaze/filemanager/utils/security/SecretKeygenEspressoTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/amaze/filemanager/ui/activities/MainActivity.java
  app/src/main/java/com/amaze/filemanager/ui/activities/superclasses/PermissionsActivity.java
  app/src/main/java/com/amaze/filemanager/ui/base/BaseBottomSheetFragment.kt
  app/src/main/java/com/amaze/filemanager/ui/views/drawer/HasherOfMenuItem.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/com/amaze/filemanager/database/MigrationTestHelper.java
  build.gradle
  commons_compress_7z/build.gradle
  file_operations/build.gradle
  portscanner/build.gradle
Labels: Issue-Task (low), Area-CodeHealth, Environment-API33
