Repository TeamAmaze/AmazeFileManager, pull requests merged in 2024-07, with the labels that each got.

#4171 fix last modified timestamps not getting preserved
  app/src/main/java/com/amaze/filemanager/asynchronous/services/CopyService.java
  app/src/main/java/com/amaze/filemanager/filesystem/HybridFile.java
Labels: Issue-Severe (high), Area-FileOperations

#4218 Migrate fingerprint decryption dialog to use AndroidX Biometrics API
  app/build.gradle
  app/src/main/java/com/amaze/filemanager/filesystem/files/EncryptDecryptUtils.java
  app/src/main/java/com/amaze/filemanager/filesystem/files/EncryptDecryptUtils.kt
  app/src/main/java/com/amaze/filemanager/ui/dialogs/DecryptFingerprintDialog.kt
  app/src/main/java/com/amaze/filemanager/ui/fragments/MainFragment.java
  app/src/main/java/com/amaze/filemanager/utils/FingerprintHandler.java
  app/src/main/java/com/amaze/filemanager/utils/FingerprintHandler.kt
  app/src/main/res/drawable-hdpi/ic_fingerprint_grey600_36dp.png
  app/src/main/res/drawable-mdpi/ic_fingerprint_grey600_36dp.png
  app/src/main/res/drawable-xhdpi/ic_fingerprint_grey600_36dp.png
  app/src/main/res/drawable-xxhdpi/ic_fingerprint_grey600_36dp.png
  app/src/main/res/drawable-xxxhdpi/ic_fingerprint_grey600_36dp.png
  app/src/main/res/layout/dialog_decrypt_fingerprint_authentication.xml
  app/src/test/java/com/amaze/filemanager/ui/dialogs/DecryptFingerprintDialogTest.kt
  gradle/libs.versions.toml
Labels: Area-UIUX, Area-CodeHealth, Area-Cryptography

#4216 Upgrade Google Play Billing library to 6.0.1
  gradle/libs.versions.toml
Labels: Area-CodeHealth, Area-Distribution
