Repository TeamAmaze/AmazeFileManager, pull requests merged in 2025-05, with the labels that each got.

#4388 Fix: Improve spacing and styling for 'Try Indexed Search' button
  app/src/main/java/com/amaze/filemanager/ui/views/appbar/SearchView.java
  app/src/main/res/drawable/button_background.xml
  app/src/main/res/drawable/ripple_button_background.xml
  app/src/main/res/layout-v21/layout_search.xml
  app/src/main/res/layout-w720dp/layout_search.xml
  app/src/main/res/layout/layout_search.xml
Labels: pr-awaiting-final-review

#4297 Grant permission dialog string issue resolved
  app/src/main/res/values/strings.xml
Labels: pr-awaiting-final-review

#4290 Option for delete permanently on single click
  app/src/main/java/com/amaze/filemanager/ui/dialogs/GeneralDialogCreation.java
  app/src/main/java/com/amaze/filemanager/ui/fragments/preferencefragments/PreferencesConstants.kt
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/behavior_prefs.xml
Labels: pr-awaiting-final-review

#4102 Update translators.xml
  app/src/main/res/values/translators.xml
Labels: pr-no-code-changes

#4404 Fix the backup preferences test
  app/src/androidTest/java/com/amaze/filemanager/test/StoragePermissionHelper.kt
  app/src/androidTest/java/com/amaze/filemanager/ui/fragments/BackupPrefsFragmentTest.kt
  app/src/androidTest/java/com/amaze/filemanager/ui/fragments/TabFragmentTest.kt
Labels: PR-No-App-Changes

#4410 transifex.yml: add Fastlane descriptions to be translatable
  transifex.yml
Labels: PR-No-Code-Changes, PR-Awaiting-Final-Review

#4380 Add guard against invalid port numbers passed into NetCopyConnectionInfo
  app/src/main/java/com/amaze/filemanager/filesystem/ftp/NetCopyConnectionInfo.kt
  app/src/test/java/com/amaze/filemanager/filesystem/ftp/NetCopyConnectionInfoTest.kt
Labels: PR-Requested-Changes
